// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ejercicio_5.src.Shared.context;

#nullable disable

namespace ejercicio_5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414105546_MigrationTest1")]
    partial class MigrationTest1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ejercicio_5.src.Modules.Bids.Infrastructure.Entiy.BidsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("AteToPickup")
                        .HasColumnType("time")
                        .HasColumnName("AteToPickup");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<int>("LoadId")
                        .HasColumnType("uuid")
                        .HasColumnName("load_id");

                    b.Property<int>("StatusBidsId")
                        .HasColumnType("uuid")
                        .HasColumnName("StatusBidsId");

                    b.Property<int>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("amount");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.HasIndex("StatusBidsId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Bids", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.CitiesOrMunicipalities.Infrastructure.Entity.CitiesOrMunicipalitiesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name");

                    b.Property<int>("StateregId")
                        .HasColumnType("int")
                        .HasColumnName("statereg_id");

                    b.Property<string>("coordinates")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coordinates");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StateregId");

                    b.ToTable("CitiesOrMunicipalities", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Countries.Infrastructure.Entity.CountriesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("iso_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("phone_code");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Customers.Infrastructure.Entity.CustomersEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Is_frequent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_frequent");

                    b.Property<int>("Person_id")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("Person_id");

                    b.ToTable("Costumers", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.DocumentCategory.Infrastructure.Entity.DocumentCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("DocumentCategory", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.DocumentStatus.Infrastructura.Entity.DocumentStatusEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("DocumentStatus", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.DocumentsDrivers.Infrastructure.Entity.DocumentDriversEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("document_status_id");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_url");

                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("type_document_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("DocumentsDrivers", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Drivers.Infrastructure.Entity.DriversEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<bool>("IsAviable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_aviable");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<string>("licenseCategory")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("license_category");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Loads.Infrastructure.Entity.LoadsEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DestinationAddress");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int")
                        .HasColumnName("DestinationCityId");

                    b.Property<string>("DestinationCords")
                        .HasColumnType("longtext");

                    b.Property<decimal>("OfferedPrice")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("OfferedPrice");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OriginAddress");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int")
                        .HasColumnName("OriginCityId");

                    b.Property<string>("OriginCords")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("PickupDate");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("TypeLoadId")
                        .HasColumnType("int")
                        .HasColumnName("TypeLoadId");

                    b.Property<decimal>("VolumeM3")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VolumeM3");

                    b.Property<decimal>("WeightTons")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("WeightTons");

                    b.HasKey("id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeLoadId");

                    b.ToTable("Loads", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.PersonStatus.Infrastructure.Entity.PersonStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("PersonStatus", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Persons.Infrastructure.Entity.PersonsEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("last_name");

                    b.Property<int>("PersonStatusId")
                        .HasColumnType("int")
                        .HasColumnName("person_status_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.HasKey("id");

                    b.HasIndex("CityId");

                    b.HasIndex("PersonStatusId");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.StatesOrRegions.Infrastructure.Entity.StatesOrRegionsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("StatesOrRegions", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.StatusBids.Infrastructure.Entity.StatusBidsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("StatusBids", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.StatusLoads.Infrastructure.Entity.StatusLoadsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("StatusLoads", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TypeDocuments", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.TypeLoad.Infrastructure.Entity.TypeLoadEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("Type_loads", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.TypesVehicles.Infrastructure.Entity.TypesVehiclesEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Axles")
                        .HasColumnType("int")
                        .HasColumnName("axles");

                    b.Property<decimal>("CapacityKg")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<decimal>("CapacityM3")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("capacity_m3");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("TypeVehicles", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Vehicles.Infrastructure.Entity.VehiclesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("plate");

                    b.Property<int>("StatusVehicleId")
                        .HasColumnType("int")
                        .HasColumnName("status_vehicle_id");

                    b.Property<int>("TypeVehicleId")
                        .HasColumnType("int")
                        .HasColumnName("type_vehicle_id");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("brand");

                    b.Property<int>("chassisNumber")
                        .HasColumnType("int")
                        .HasColumnName("chassis_number");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusVehicleId");

                    b.HasIndex("TypeVehicleId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.VehiclesStatus.Infrastructure.Entity.VehiclesStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Bids.Infrastructure.Entiy.BidsEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.Drivers.Infrastructure.Entity.DriversEntity", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.Loads.Infrastructure.Entity.LoadsEntity", null)
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.StatusBids.Infrastructure.Entity.StatusBidsEntity", null)
                        .WithMany()
                        .HasForeignKey("StatusBidsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.Vehicles.Infrastructure.Entity.VehiclesEntity", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.CitiesOrMunicipalities.Infrastructure.Entity.CitiesOrMunicipalitiesEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.StatesOrRegions.Infrastructure.Entity.StatesOrRegionsEntity", null)
                        .WithMany()
                        .HasForeignKey("StateregId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Customers.Infrastructure.Entity.CustomersEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.Persons.Infrastructure.Entity.PersonsEntity", null)
                        .WithMany()
                        .HasForeignKey("Person_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.DocumentsDrivers.Infrastructure.Entity.DocumentDriversEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.DocumentStatus.Infrastructura.Entity.DocumentStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.Drivers.Infrastructure.Entity.DriversEntity", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", null)
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Drivers.Infrastructure.Entity.DriversEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.Persons.Infrastructure.Entity.PersonsEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Loads.Infrastructure.Entity.LoadsEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.Customers.Infrastructure.Entity.CustomersEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.CitiesOrMunicipalities.Infrastructure.Entity.CitiesOrMunicipalitiesEntity", null)
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.CitiesOrMunicipalities.Infrastructure.Entity.CitiesOrMunicipalitiesEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.StatusLoads.Infrastructure.Entity.StatusLoadsEntity", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.TypeLoad.Infrastructure.Entity.TypeLoadEntity", null)
                        .WithMany()
                        .HasForeignKey("TypeLoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Persons.Infrastructure.Entity.PersonsEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.CitiesOrMunicipalities.Infrastructure.Entity.CitiesOrMunicipalitiesEntity", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.PersonStatus.Infrastructure.Entity.PersonStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.StatesOrRegions.Infrastructure.Entity.StatesOrRegionsEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.Countries.Infrastructure.Entity.CountriesEntity", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.DocumentCategory.Infrastructure.Entity.DocumentCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ejercicio_5.src.Modules.Vehicles.Infrastructure.Entity.VehiclesEntity", b =>
                {
                    b.HasOne("ejercicio_5.src.Modules.Persons.Infrastructure.Entity.PersonsEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.VehiclesStatus.Infrastructure.Entity.VehiclesStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("StatusVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ejercicio_5.src.Modules.TypesVehicles.Infrastructure.Entity.TypesVehiclesEntity", null)
                        .WithMany()
                        .HasForeignKey("TypeVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
